version: "3.5"
services:
  spring-boot:
    image: spring-boot
    build:
      context: .
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ${APPLICATION_ROOT_FOLDER}:/usr/src/mymaven
    depends_on:
        - postgresql

  postgresql:
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"